### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by johmarjac** [RytisLT/RoE#1]
Hi,

still launcher only says Coming soon, how to fix

**Comment by RytisLT** [comment]
What? That is impossible. Can you please attach screenshot? Are you sure you've downloaded the right binaries from here: https://github.com/RytisLT/RoE/releases? Did you download version 1.0.2? There's literally no "Coming soon" string in the whole repository :)

**Comment by johmarjac** [comment]
Sorry, yes I meant it says Coming Soon in Garena.. I should have been more clearly.

**Comment by RytisLT** [comment]
OK this makes more sense. Make sure your region in Garena is set to Thailand. I need to check whether I can add this check to the helper.

**Comment by johmarjac** [comment]
@RytisLT it is set ti thailand yes, still not an option to install.

**Comment by RytisLT** [comment]
HM.. that's interesting, where are you located geographically? I'll need to test this using appropriate proxy when I get back home from work ;)

**Comment by johmarjac** [comment]
@RytisLT Yes, Germany is correct. Would be awesome if you could figure that out.

**Comment by RytisLT** [comment]
OK, no proxy needed then :) I'll check with a fresh Garena account, maybe they changed something...

**Comment by johmarjac** [comment]
My account is also fresh yes, maybe that's an issue. Also I dont get properly why it should be playable since its a closed beta? I dont have any invitation or sth.

**Comment by johmarjac** [comment]
@RytisLT  could you do me a favor and install Fiddler 4 and sniff the https traffic of garena?
Best would be if you temporary move game installation to another location, so that garena wants to install it again so we are on the same state. Maybe I can use your sniffed data to modify the https requests and then be able to isntall

**Comment by RytisLT** [comment]
I've did some googling and apparently the Thailand beta is being killed on June 10th. It's probably why you're not allowed to download the game anymore. Not sure what it means for the game. Maybe their shutting down server before the launch, maybe Tencent is killing the game, well have to wait and see
